# Generated by Django 4.0.5 on 2022-06-17 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=50)),
                ('brands', models.TextField(help_text='Brands of the product')),
                ('code', models.BigIntegerField(help_text='Bar code of the product')),
                ('original_id', models.BigIntegerField(db_index=True, unique=True)),
                ('quantity', models.CharField(max_length=30)),
                ('image_thumb_url', models.URLField()),
                ('image_url', models.URLField()),
                ('ingredients_text', models.TextField()),
                ('keywords', models.TextField()),
                ('nutriments', models.JSONField()),
                ('nutriscore_grade', models.CharField(max_length=2)),
                ('stores', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('is_already_read', models.BooleanField(default=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='L_Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('original_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_products', to='products.product')),
                ('substitute_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_products', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('products', models.ManyToManyField(related_name='categories', to='products.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
